Alert
Rockyraven/boostweb-ui pull request #1
Opened 2022-02-02 15:10 UTC by Rockyraven

2022-02-02 16:33 UTC, arjun-computer-geek requested changes

2022-02-02 16:33 UTC, arjun-computer-geek commented on component/alert/alert.css
> +     /* display: inline; */
remove these commented or unused codes

2022-02-02 16:33 UTC, arjun-computer-geek commented on component/alert/alert.css
> +    --primary-color: #ff3b30;
use these color's variables in style.css . Thereafter you can use it anywhere.

2022-02-02 16:33 UTC, arjun-computer-geek commented on component/alert/alert.css
> +     margin-top: 15px;
use rem instead px

2022-02-02 16:33 UTC, arjun-computer-geek commented on component/alert/alert.css
> +        background-color: rgb(245, 102, 91);
hex code would be better

2022-02-02 16:33 UTC, arjun-computer-geek commented on component/alert/alert.css
> + /* .all-containant{
remove these too

2022-02-02 16:33 UTC, arjun-computer-geek commented on component/alert/alert.html
> +<script src="https://kit.fontawesome.com/a076d05399.js"></script>
write comments. it would be better for others

2022-02-02 16:33 UTC, arjun-computer-geek commented on component/slidebaar.css
> +
why this extra spacing? Any reason?

2022-02-02 16:33 UTC, arjun-computer-geek commented on index.html
> +            <a href="http://127.0.0.1:5500/alert.html">Explore More</a>
don't add localhost references in href

2022-02-04 16:49 UTC, pratik-kumar-sahu reviewed
you can use "Prettier" in vs code to get rid of uneven spaces in your code. Everything else is fine. Nice work.

2022-02-04 16:49 UTC, pratik-kumar-sahu commented on alert.html
> +            <a href="#"> <i class="fab fa-github" style="font-size:40px"> </i></a>
try to minimize repetitive codes. Use classes instead of inline styling wherever possible.

2022-02-07 18:45 UTC, Shubhamkr2610 commented on style.css
>  }
remove unused code

2022-02-07 18:45 UTC, Shubhamkr2610 commented on style.css
>  }
I think you should you color with variable name

2022-02-07 18:49 UTC, Shubhamkr2610 commented on component/alert/alert.css
>          background-color: rgb(245, 102, 91);
use color name with variable

2022-02-08 19:06 UTC, merged